### ISSUE TITLE
[BUG] apiError 미들웨어

### ISSUE THREAD

**Issue by joseph0926** [Selody-project/Backend#67]
### Description

`const apiError = (error, req, res, next) => res.status(error.status).json({ error: error.message });`
에서 error.status가 "RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined"오류를 발생시킵니다

한번 확인 부탁드립니다

에러 전체 로그

GET /api/auth/token/verify 500 11.346 ms - 1337
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (C:\Users\joseph0926\Downloads\Front_Back_end\Project\Team_Project\xern\Backend\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (C:\Users\joseph0926\Downloads\Front_Back_end\Project\Team_Project\xern\Backend\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (C:\Users\joseph0926\Downloads\Front_Back_end\Project\Team_Project\xern\Backend\node_modules\express\lib\response.js:278:15)
    at apiError (C:\Users\joseph0926\Downloads\Front_Back_end\Project\Team_Project\xern\Backend\src\middleware\apiError.js:2:70)
    at Layer.handle_error (C:\Users\joseph0926\Downloads\Front_Back_end\Project\Team_Project\xern\Backend\node_modules\express\lib\router\layer.js:71:5

**Comment by joseph0926** [comment]
임의로 특정 숫자 (ex, 401)로 지정하였다니 오류가 발생하지 않았습니다

**Comment by GGANCC1** [comment]
코드 문법 오류로 인한 런타임 에러로 보입니다. 카톡으로 답변드린 라인 수정 이후에, 따로 추가적인 문제 없으시면 이슈 닫아주시면 감사하겠습니다~!
